Handle unknown status, improve tests

diff --git a/hooks/test b/hooks/test
--- a/hooks/test
+++ b/hooks/test
@@ -1,11 +1,39 @@
-#!/bin/bash -xe
+#!/bin/bash -e
 
 . ./hooks/env
 
-CID=$(docker run -d $IMAGE_NAME)
-sleep 15s
-# Message is: Please visit https://www.dropbox.com/cli_link_nonce?nonce=_____ to link this device.
-LOGS="$(docker logs $CID)"
-docker rm -f $CID
-echo $LOGS | grep -iq 'please visit.*to link'
+function retry {
+  local retry_max=$1
+  shift
 
+  local count=$retry_max
+  while [ $count -gt 0 ]; do
+    "$@" && break
+    count=$(($count - 1))
+    sleep 3
+  done
+
+  [ $count -eq 0 ] && {
+    echo "Retry failed [$retry_max]: $@" >&2
+    return 1
+  }
+  return 0
+}
+
+function test_link_message {
+    # Message is: Please visit https://www.dropbox.com/cli_link_nonce?nonce=_____ to link this device.
+    docker logs ${CID} | grep -iq 'please visit.*to link'
+}
+
+function finish {
+    if [ -n "${CID}" ]; then
+        docker logs ${CID}
+        docker rm -f ${CID}
+    fi
+}
+trap finish EXIT
+
+export CID="$(docker run -d -e STATUS=Yes $IMAGE_NAME)"
+
+sleep 15s
+retry 10 test_link_message
